name: erad-2022-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyter-book
  - numpy
  - scipy
  - matplotlib
  - cartopy
  - pandas
  - xarray
  - wradlib=1.16.2
  - dask
  - tqdm
  - hvplot
  - rioxarray
  - geopandas
  - datashader
  - pyart=1.12.7
  - pyrad_arm
  - cookiecutter
  # this is needed for baltrad compilation
  - compilers
  - make
  - gnuconfig
  - bash
  - libaec
  - coreutils
  - autoconf
  - automake
  - tar
  - libblas=*=*netlib
  - liblapacke=*=*netlib
  # this is needed for notebooks
  - pip
  - pyviz_comms>=2.0
  - nbstripout
  - zip
  - pip:
      - sphinx-pythia-theme
