name: erad-2022-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyter-book
  - numpy
  - scipy
  - matplotlib
  - cartopy
  - pandas
  - xarray
  - wradlib
  - arm_pyart
  # this is needed for baltrad compilation
  - compilers
  - make
  - gnuconfig
  - bash
  - libaec
  - coreutils
  - autoconf
  - automake
  - tar
  - libblas=*=*netlib
  - liblapacke=*=*netlib
