#!/bin/bash

# installing extensions
# kmuehlbauer: this seems to not work currently
jupyter labextension install @pyviz/jupyterlab_pyviz \
                             jupyter-leaflet


# INSTALLING BALTRAD
CONDA_DIR=/srv/conda
RADARENV=notebook
CONDA_PREFIX=$CONDA_DIR/envs/$RADARENV

# enter user home folder
cd ~
echo "current directory: $PWD"

# export, needed for subsequent installation process
export BALTRAD_INSTALL_ROOT=$PWD

# have it available in every new bash instance
echo "export CONDA_DIR=$CONDA_DIR" >> ~/.profile
echo "export RADARENV=$RADARENV" >> ~/.profile
echo "export CONDA_PREFIX=$CONDA_PREFIX" >> ~/.profile

# install baltrad
cd $BALTRAD_INSTALL_ROOT
bash -l $BALTRAD_INSTALL_ROOT/install/baltrad/install_baltrad.sh

# copy kernel.json
cp $BALTRAD_INSTALL_ROOT/binder/kernel.json $CONDA_PREFIX/share/jupyter/kernels/python3/.
